### PR TITLE
Rd/develop

### PR DESCRIPTION
**Pull request by Senbazuru1075**
Need some help with memory management. That's the part I didn't understand. I also don't get how to do the functional programming style for some of the properties of FPUICollectionViewDatasource. They're supposed to take a function, but there are no complementary functions to go with them in the library.

### CODE REVIEW

**Review by cjc8 — CHANGES_REQUESTED** [review]

**Comment by Senbazuru1075** [comment]
@cjc8 Do I need to add the other properties or do you just want the 3 properties already in there from `FPUICollectionViewDataSource` there are no complementary functions to plug in for them. I can add stubs for the properties, but I'm not exactly sure what I'm supposed to be doing in the implementation for it. I need to know the purpose to implement the stubs well.

**Comment by cjc8** [comment]
> @cjc8 Do I need to add the other properties or do you just want the 3 properties already in there from `FPUICollectionViewDataSource` there are no complementary functions to plug in for them. I can add stubs for the properties, but I'm not exactly sure what I'm supposed to be doing in the implementation for it. I need to know the purpose to implement the stubs well.

Can you link me to the three properties you're talking about?

**Comment by Senbazuru1075** [comment]
Screen Shot 2022-02-24 at 12 09 29 PM

These properties here.

**Review by cjc8 — COMMENTED** [review]
Once we get the CI to pass, we can get this merged.  Looks like something in FlexCollectionDataSourceTests is failing.

**Pull request merged**
